#!/usr/bin/env python3
"""Embed a plugin's Resources/ image assets into its generated JSFXResources.h.

Standard library only. Paths are UTF-8, deterministic and collision checked.
Resources/ is a sibling of src/. Static filename: image references beside the
source are also bundled. Audio filename slots remain exclusively DSP-owned.
"""
from __future__ import annotations
import argparse
import hashlib
import re
from pathlib import Path

IMAGE_SUFFIXES = {".png", ".jpg", ".jpeg", ".gif"}
MAX_FILE_BYTES = 16 * 1024 * 1024
MAX_TOTAL_BYTES = 64 * 1024 * 1024

def _cpp_utf8(text: str) -> str:
    return '"' + ''.join(f'\\{b:03o}' for b in text.encode('utf-8')) + '"'

def normalize_name(name: str) -> str:
    name = name.replace('\\', '/')
    while name.startswith('./'):
        name = name[2:]
    for prefix in ('../Resources/', 'Resources/'):
        if name.startswith(prefix):
            name = name[len(prefix):]
            break
    parts: list[str] = []
    for part in name.split('/'):
        if part == '..' and parts and parts[-1] != '..':
            parts.pop()
        elif part and part != '.':
            parts.append(part)
    return '/'.join(parts)

def write_gfx_resources(jsfx_path: Path, jsfx_text: str, out_header: Path) -> Path:
    source = jsfx_path.resolve().parent
    root = source.parent / 'Resources'
    assets: dict[str, Path] = {}
    folded: dict[str, str] = {}
    def add(name: str, path: Path) -> None:
        normalized = normalize_name(name)
        if not normalized or path.suffix.lower() not in IMAGE_SUFFIXES:
            return
        if path.is_symlink():
            raise ValueError(f'Resource symlinks are not packaged: {path}')
        previous = assets.get(normalized)
        if previous is not None and previous.resolve() != path.resolve():
            raise ValueError(f'Duplicate GFX resource name {normalized}: {previous} and {path}')
        key = normalized.casefold()
        if key in folded and folded[key] != normalized:
            raise ValueError(f'Case-ambiguous GFX resource names: {folded[key]} and {normalized}')
        assets[normalized] = path
        folded[key] = normalized
    if root.is_dir():
        for path in sorted(root.rglob('*')):
            if path.is_file():
                if not path.resolve().is_relative_to(root.resolve()):
                    raise ValueError(f'Resource escapes its directory: {path}')
                add(path.relative_to(root).as_posix(), path)
    preamble = re.split(r'^\s*@', jsfx_text, maxsplit=1, flags=re.MULTILINE)[0]
    for match in re.finditer(r'^\s*filename:\s*(\d+)\s*,\s*(.*?)\s*$', preamble, re.MULTILINE):
        if not 0 <= int(match[1]) < 128:
            continue
        name = match[2]
        path = source / name
        if not path.is_file():
            path = root / normalize_name(name)
        if path.is_file():
            add(name, path)
    # Validate sizes before reading assets or creating the output.
    total = 0
    for path in assets.values():
        size = path.stat().st_size
        if size > MAX_FILE_BYTES:
            raise ValueError(f'GFX resource exceeds 16 MiB: {path}')
        total += size
    if total > MAX_TOTAL_BYTES:
        raise ValueError('Packaged GFX resources exceed 64 MiB')
    lines = ['// Generated by embed_gfx_resources.py. Do not edit.\n#pragma once\n',
             'namespace jsfx_gfx_resources {\n',
             f'static constexpr const char* kSourceDir={_cpp_utf8(source.as_posix())};\n']
    entries = []
    for name, path in sorted(assets.items()):
        data = path.read_bytes()
        ident = 'res_' + hashlib.sha256(name.encode()).hexdigest()[:16]
        lines.append(f'static const unsigned char {ident}[]={{\n')
        for i in range(0, len(data), 24):
            lines.append(','.join(str(b) for b in data[i:i+24]) + ',\n')
        if not data:
            lines.append('0,\n')
        lines.append('};\n')
        entries.append(f'{{{_cpp_utf8(name)},{ident},{len(data)}}}')
    if entries:
        lines.append('static const EmbeddedResource kEntries[]={\n' + ',\n'.join(entries) + '\n};\n')
    else:
        lines.append('static constexpr const EmbeddedResource* kEntries=nullptr;\n')
    lines.append(f'static constexpr size_t kEntryCount={len(entries)};\n}}\n')
    output = ''.join(lines)
    out_header.parent.mkdir(parents=True, exist_ok=True)
    if not out_header.exists() or out_header.read_text(encoding='utf-8') != output:
        temporary = out_header.with_suffix(out_header.suffix + '.tmp')
        temporary.write_text(output, encoding='utf-8')
        temporary.replace(out_header)
    return out_header

def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('source', type=Path)
    parser.add_argument('output', type=Path)
    args = parser.parse_args()
    write_gfx_resources(args.source, args.source.read_text(encoding='utf-8-sig'), args.output)

if __name__ == '__main__':
    main()
